#FROM quay.io/centos-bootc/centos-bootc:c9s
FROM quay.io/fedora/fedora-bootc:41
#FROM registry.redhat.io/rhel9/rhel-bootc:9.4

#install the lamp components
RUN dnf install -y php nginx httpd mariadb mariadb-server php-fpm php-mysqlnd && dnf clean all

#start the services automatically on boot
RUN systemctl enable httpd mariadb php-fpm

#create an awe inspiring home page!
RUN echo '<h1 style="text-align:center;">Welcome to image mode for RHEL</h1> <?php phpinfo(); ?>' >> /var/www/html/index.php

